server:
  port: 9003

spring:
  jackson:
        serialization.write_dates_as_timestamps: false
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
            #hibernate.cache.region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
            hibernate.javax.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
            javax.persistence.sharedCache.mode: ALL

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/csoftz-books-info?currentSchema=books-info
    username: postgres
    password: Ceiba1234!

logging:
  level:
    root:
    #org.hibernate: debug
    #org.springframework: debug
    com.csoftz.books.info : debug
